Repository cloudbees/cloudbees-jenkins-x-versions, pull requests merged in 2019-07, with the labels that each got.

#1 upgrade chart versions
  charts/bitnami/external-dns.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/stable/external-dns.yml
  charts/stable/grafana.yml
  charts/stable/nginx-ingress.yml
  charts/stable/prometheus.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#8 upgrade chart versions
  charts/bitnami/external-dns.yml
  charts/jenkins-x/jenkins-x-platform.yml
  charts/jenkins-x/jx-build-templates.yml
  charts/jenkins-x/prow.yml
  charts/stable/external-dns.yml
  charts/stable/grafana.yml
  charts/stable/nginx-ingress.yml
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-helm3.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
Labels: size/M

#9 Delete external-dns.yml
  charts/bitnami/external-dns.yml
Labels: size/XS

#7 feat: enable boot based bdd tests
  jenkins-x-boot-gke.yml
  jenkins-x-boot-local.yml
  jenkins-x-eksclassic.yml
  jenkins-x-ekstekton.yml
  jenkins-x-gitops.yml
  jenkins-x-ng.yml
  jenkins-x-prow.yml
  jenkins-x-static-gke-us-east1-b.yml
  jenkins-x-static.yml
  jenkins-x-tekton.yml
  jenkins-x-terraform.yml
  jenkins-x-tiller.yml
  jx/bdd/boot-gke/README.md
  jx/bdd/boot-gke/ci.sh
  jx/bdd/boot-gke/cluster.yaml
  jx/bdd/boot-gke/jx-requirements.yml
  jx/bdd/boot-gke/parameters.yaml
  jx/bdd/boot-local/ci.sh
  jx/bdd/boot-local/jx-requirements.yml
  jx/bdd/eksclassic/README.md
  jx/bdd/eksclassic/ci.sh
  jx/bdd/eksclassic/cluster.yaml
  jx/bdd/ekstekton/README.md
  jx/bdd/ekstekton/ci.sh
  jx/bdd/ekstekton/cluster.yaml
  jx/bdd/gitops/README.md
  jx/bdd/gitops/ci.sh
  jx/bdd/gitops/cluster.yaml
  jx/bdd/helm3/README.md
  jx/bdd/helm3/ci.sh
  jx/bdd/helm3/cluster.yaml
  jx/bdd/knative-build/README.md
  jx/bdd/knative-build/ci.sh
  jx/bdd/knative-build/cluster.yaml
  jx/bdd/ng/README.md
  jx/bdd/ng/ci.sh
  jx/bdd/ng/cluster.yaml
  jx/bdd/static-gke-us-east1-b/README.md
  jx/bdd/static-gke-us-east1-b/ci.sh
  jx/bdd/static-gke-us-east1-b/cluster.yaml
  jx/bdd/static/README.md
  jx/bdd/static/ci.sh
  jx/bdd/static/cluster.yaml
  jx/bdd/tekton/README.md
  jx/bdd/tekton/ci.sh
  jx/bdd/tekton/cluster.yaml
  jx/bdd/terraform/cluster.yaml
  jx/bdd/tiller/README.md
  jx/bdd/tiller/ci.sh
  jx/bdd/tiller/cluster.yaml
Labels: size/XL

#10 feat: add a html xunit generation step
  docker/gcr.io/jenkinsxio/builder-dlang.yml
  docker/gcr.io/jenkinsxio/builder-go-maven.yml
  docker/gcr.io/jenkinsxio/builder-go.yml
  docker/gcr.io/jenkinsxio/builder-gradle.yml
  docker/gcr.io/jenkinsxio/builder-gradle4.yml
  docker/gcr.io/jenkinsxio/builder-gradle5-java11.yml
  docker/gcr.io/jenkinsxio/builder-gradle5.yml
  docker/gcr.io/jenkinsxio/builder-jx.yml
  docker/gcr.io/jenkinsxio/builder-maven-32.yml
  docker/gcr.io/jenkinsxio/builder-maven-java11.yml
  docker/gcr.io/jenkinsxio/builder-maven-nodejs.yml
  docker/gcr.io/jenkinsxio/builder-maven.yml
  docker/gcr.io/jenkinsxio/builder-nodejs.yml
  jenkins-x-boot-gke.yml
  jx/bdd/boot-gke/ci.sh
  jx/bdd/boot-gke/jx-requirements.yml
Labels: size/M

#14 Bump to boot config 1.0.1
  git/github.com/jenkins-x/jenkins-x-boot-config.yml
Labels: size/XS
