Repository cloudbees/cloudbees-jenkins-x-versions, pull requests merged in 2020-01, with the labels that each got.

#102 tests: add jxui bdd tests suite
  jenkins-x-boot-gke-jxui.yml
  jx/bdd/boot-gke-jxui/ci.sh
  jx/bdd/boot-gke-jxui/cluster.yaml
  jx/bdd/boot-gke-jxui/jx-requirements.yml
  jx/bdd/boot-gke-jxui/report.sh
Labels: lgtm, size/L

#116 chore: add romain and hardy to reviewers
  OWNERS
Labels: lgtm, size/XS

#121 chore: publish test report and screenshots in case of tests failure
  jenkins-x-boot-gke-jxui.yml
  jx/bdd/boot-gke-jxui/ci.sh
  jx/bdd/boot-gke-jxui/report.sh
Labels: approved, lgtm, size/M

#111 WIP feat: enable EKS BDD tests
  jenkins-x-boot-eks.yml
  jx/bdd/boot-eks/README.md
  jx/bdd/boot-eks/ci.sh
  jx/bdd/boot-eks/cluster.yaml
  jx/bdd/boot-eks/jx-requirements.yml
  jx/bdd/boot-eks/report.sh
Labels: do-not-merge/work-in-progress, size/L

#125 feat: enable TLS when testing upgrades
  jx/bdd/boot-gke-vault-upgrade/ci.sh
  jx/bdd/boot-gke-vault-upgrade/cluster.yaml
  jx/bdd/boot-gke-vault-upgrade/jx-requirements.yml
Labels: approved, lgtm, size/M

#132 chore: Create a different domain for testing to prevent clashes
  jenkins-x-boot-gke-vault-upgrade.yml
  jx/bdd/boot-gke-vault-upgrade/jx-requirements.yml
Labels: size/XS

#80 fix: Test UI during version stream tests
  jenkins-x-boot-gke-vault.yml
  jenkins-x-boot-gke.yml
  jx/bdd/boot-gke-vault/ci.sh
  jx/bdd/boot-gke/ci.sh
Labels: size/S

#139 feat: make bdd tests reporting work
  jenkins-x-boot-eks.yml
  jx/bdd/boot-eks/ci.sh
  jx/bdd/boot-eks/report.sh
Labels: approved, lgtm, size/S

#142 chore: use latest builder-go-nodejs in boot-gke-jxui
  jenkins-x-boot-gke-jxui.yml
Labels: lgtm, size/XS

#151 chore: Remove the UI test as it now runs in its own context
  jx/bdd/boot-gke-vault/ci.sh
Labels: size/XS
